// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/RipperAcskt/innotaxiorder/internal/service (interfaces: AnalystService)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	proto "github.com/RipperAcskt/innotaxi/pkg/proto"
	gomock "github.com/golang/mock/gomock"
)

// MockAnalystService is a mock of AnalystService interface.
type MockAnalystService struct {
	ctrl     *gomock.Controller
	recorder *MockAnalystServiceMockRecorder
}

// MockAnalystServiceMockRecorder is the mock recorder for MockAnalystService.
type MockAnalystServiceMockRecorder struct {
	mock *MockAnalystService
}

// NewMockAnalystService creates a new mock instance.
func NewMockAnalystService(ctrl *gomock.Controller) *MockAnalystService {
	mock := &MockAnalystService{ctrl: ctrl}
	mock.recorder = &MockAnalystServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAnalystService) EXPECT() *MockAnalystServiceMockRecorder {
	return m.recorder
}

// SetRating mocks base method.
func (m *MockAnalystService) SetRating(arg0 context.Context, arg1 *proto.Rating) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetRating", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetRating indicates an expected call of SetRating.
func (mr *MockAnalystServiceMockRecorder) SetRating(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRating", reflect.TypeOf((*MockAnalystService)(nil).SetRating), arg0, arg1)
}
